### ISSUE TITLE
Typo in evaluate_metrics scripts?

### ISSUE THREAD

**Issue by kevinvlowell** [BUserName/NCTI#1]
Thanks for your great work with this paper! I noticed that when calculating the NCTI scores in the evaluate_metric scripts, you use the following line of code:

`score_dict[model] = mascore + mcscore - cpscore`

However, in your paper, Equation 12 seems to indicate that this should instead be:

`score_dict[model] = mascore + mcscore + cpscore`

Is this a typo in the code, or am I misunderstanding the connection between those two formulas?

**Comment by BUserName** [comment]
Thanks for your interest in our work. And the short answer is no.

If we have a look Eq.5 in the paper, we will notice a '-' before the summation of the nuclear norm. By substituting Eq.5 in 12, we will have 

`score_dict[model] = mascore + mcscore - cpscore`

**Comment by kevinvlowell** [comment]
Ah I must've glanced over that too quickly, I see that now. Thank you!

**Comment by kevinvlowell** [comment]
Ah I must've glanced over that too quickly, I see that now. Thank you!
